// SPDX-License-Identifier: MIT
// Copyright (c) 2026 James Lewis <james@baldengineer.com>

/*
 * ArbDraw editable waveform defaults.
 *
 * Keep this as a plain JavaScript object so it loads when index.html is opened
 * directly from disk. Values use volts, hertz, and degrees.
 */
globalThis.ARBDRAW_DEFAULTS = {
  bridgeUrl: 'http://127.0.0.1:8876',
  highLevelV: 500,
  highLevelUnit: 'mV',
  lowLevelV: -500,
  lowLevelUnit: 'mV',
  offsetV: 0,
  offsetUnit: 'V',
  amplitudeVpp: 10,
  amplitudeUnit: 'Vpp',
  sampleRateMSa: 1250,
  sampleRateUnit: 'MSa/s',
  sampleCount: 1000,
  sampleCountUnit: 'pts',
  waveformType: 'serial',
  nCycles: 1,
  frequencyHz: 2.5,
  frequencyUnit: 'kHz',
  periodUnit: 'us',
  tsResolutionUnit: 'ns',
  phaseDegrees: 0,
  phaseUnit: '°',
  dutyCyclePercent: 50,
  symmetryPercent: 50,
  dutyCycleUnit: '%',
  riseTimeSeconds: 0,
  riseTimeUnit: 'ns',
  fallTimeSeconds: 0,
  fallTimeUnit: 'ns',
  filtersEnabled: true,
  noiseColor: 'white',
  noisePercent: 1,
  noisePercentMax: 10,
  serialProtocol: 'UART',
  serialBaud: 57600,
  serialWordSize: 8,
  serialBitOrder: 'LSB',
  serialInvertData: false,
  serialParity: 'none',
  serialStartBit: true,
  serialPreIdleBits: 1,
  serialPostIdleBits: 10,
  serialStopBits: 1,
  serialPayload: 'Hello World',
  serialBinaryPattern: '',
  serial_debug: false,
  editor_tool: 'Edit',
  editorColor: '#7bffb2',
  waveformColor: '#ffe45e',
  waveformVerticalDivisions: 10,
};
