const canvas = document.querySelector('#waveCanvas');
const ctx = canvas.getContext('2d');
const scopeCanvas = document.querySelector('#scopeCanvas');
const scopeCtx = scopeCanvas.getContext('2d');
function normalizeDefaults(source={}){
  const finite=(key,fallback)=>Number.isFinite(Number(source[key]))?Number(source[key]):fallback;
  const color=(key,fallback)=>/^#[0-9a-f]{6}$/i.test(String(source[key]||''))?String(source[key]):fallback;
  const voltageUnits={V:1,mV:.001,'µV':.000001},amplitudeUnits={Vpp:1,mVpp:.001,'µVpp':.000001},frequencyUnits={mHz:.001,Hz:1,kHz:1e3,MHz:1e6,GHz:1e9},periodUnits={Ms:1e6,s:1,ms:.001,'µs':1e-6,ns:1e-9},sampleRateUnits={'Sa/s':1e-6,'kSa/s':.001,'MSa/s':1,'GSa/s':1e3},sampleCountUnits={pts:1,kpts:1e3,Mpts:1e6};
  const unit=(key,units,fallback)=>Object.hasOwn(units,source[key])?source[key]:fallback;
  const highLevelUnit=unit('highLevelUnit',voltageUnits,'V'),lowLevelUnit=unit('lowLevelUnit',voltageUnits,'V'),offsetUnit=unit('offsetUnit',voltageUnits,'V'),amplitudeUnit=unit('amplitudeUnit',amplitudeUnits,'Vpp'),frequencyUnit=unit('frequencyUnit',frequencyUnits,'Hz'),periodUnit=unit('periodUnit',periodUnits,'µs'),sampleRateUnit=unit('sampleRateUnit',sampleRateUnits,'MSa/s'),sampleCountUnit=unit('sampleCountUnit',sampleCountUnits,'pts');
  const offsetV=finite('offsetV',0)*voltageUnits[offsetUnit],amplitudeVpp=Math.max(0,finite('amplitudeVpp',10)*amplitudeUnits[amplitudeUnit]);
  let highLevelV=finite('highLevelV',(offsetV+amplitudeVpp/2)/voltageUnits[highLevelUnit])*voltageUnits[highLevelUnit],lowLevelV=finite('lowLevelV',(offsetV-amplitudeVpp/2)/voltageUnits[lowLevelUnit])*voltageUnits[lowLevelUnit];
  if(highLevelV<lowLevelV)[highLevelV,lowLevelV]=[lowLevelV,highLevelV];
  return Object.freeze({highLevelV,lowLevelV,offsetV,amplitudeVpp,highLevelUnit,lowLevelUnit,offsetUnit,amplitudeUnit,frequencyUnit,periodUnit,sampleRateUnit,sampleCountUnit,phaseUnit:String(source.phaseUnit||'°'),dutyCycleUnit:String(source.dutyCycleUnit||'%'),sampleRateMSa:Math.max(.000001,finite('sampleRateMSa',2500/sampleRateUnits[sampleRateUnit])*sampleRateUnits[sampleRateUnit]),sampleCount:Math.max(2,Math.round(finite('sampleCount',10000/sampleCountUnits[sampleCountUnit])*sampleCountUnits[sampleCountUnit])),frequencyHz:Math.max(.000001,finite('frequencyHz',750000/frequencyUnits[frequencyUnit])*frequencyUnits[frequencyUnit]),phaseDegrees:finite('phaseDegrees',0),dutyCyclePercent:Math.min(95,Math.max(5,finite('dutyCyclePercent',50))),editorColor:color('editorColor','#7bffb2'),waveformColor:color('waveformColor','#ffe45e')});
}
const DEFAULT_VALUES=normalizeDefaults(globalThis.ARBDRAW_DEFAULTS);
const voltageScaleByLabel={V:1,mV:.001,'µV':.000001},amplitudeScaleByLabel={Vpp:1,mVpp:.001,'µVpp':.000001},frequencyScaleByLabel={mHz:.001,Hz:1,kHz:1e3,MHz:1e6,GHz:1e9},periodScaleByLabel={Ms:1e6,s:1,ms:.001,'µs':1e-6,ns:1e-9};
let amplitudeUnitScale=amplitudeScaleByLabel[DEFAULT_VALUES.amplitudeUnit];
const voltageUnitScales={highInput:voltageScaleByLabel[DEFAULT_VALUES.highLevelUnit],lowInput:voltageScaleByLabel[DEFAULT_VALUES.lowLevelUnit],offsetInput:voltageScaleByLabel[DEFAULT_VALUES.offsetUnit]};
let frequencyUnitScale=frequencyScaleByLabel[DEFAULT_VALUES.frequencyUnit],periodUnitScale=periodScaleByLabel[DEFAULT_VALUES.periodUnit];
function displayAmplitude(volts){return Number((volts/amplitudeUnitScale).toPrecision(10))}
function displayVoltage(inputId,volts){return Number((volts/voltageUnitScales[inputId]).toPrecision(10))}
function inputVoltage(inputId){return +$(inputId).value*voltageUnitScales[inputId]}
function displayFrequency(hertz){return Number((hertz/frequencyUnitScale).toPrecision(10))}
function inputFrequency(){return +$('frequencyInput').value*frequencyUnitScale}
function displayPeriod(hertz){return Number(((1/hertz)/periodUnitScale).toPrecision(10))}
function inputPeriodFrequency(){return 1/(+$('periodInput').value*periodUnitScale)}
function createDefaultDocument(){const durationMs=DEFAULT_VALUES.sampleCount/(DEFAULT_VALUES.sampleRateMSa*1000);return {schema:'arbdraw.waveform',version:1,name:'Waveform 01',waveform:{type:'sine',highVoltage:DEFAULT_VALUES.highLevelV,lowVoltage:DEFAULT_VALUES.lowLevelV,durationMs,sampleRateMSa:DEFAULT_VALUES.sampleRateMSa,frequencyHz:DEFAULT_VALUES.frequencyHz,cycles:DEFAULT_VALUES.frequencyHz*durationMs/1000,phaseDegrees:DEFAULT_VALUES.phaseDegrees,dutyCyclePercent:DEFAULT_VALUES.dutyCyclePercent,sampleCount:DEFAULT_VALUES.sampleCount,values:[]}}}
let projectDocument=createDefaultDocument();
const state = { tool:'pencil', zoom:1, history:[], redo:[], drawing:false, lineStart:null };
const scopeState={voltsPerDiv:2,verticalPosition:0,timePerDivMs:null,cycles:2,fitted:false};
let scopeVoltageUnitScale=1;
let scopePositionUnitScale=1;
let scopeTimeUnitScaleMs=.000001;
const documentFields={type:'type',high:'highVoltage',low:'lowVoltage',duration:'durationMs',sampleRate:'sampleRateMSa',frequency:'frequencyHz',cycles:'cycles',phase:'phaseDegrees',duty:'dutyCyclePercent',samples:'sampleCount',data:'values'};
Object.entries(documentFields).forEach(([stateKey,documentKey])=>Object.defineProperty(state,stateKey,{get:()=>projectDocument.waveform[documentKey],set:value=>projectDocument.waveform[documentKey]=value}));
const titles = {sine:'Sine wave',square:'Square wave',triangle:'Triangle wave',ramp:'Ramp wave',pulse:'Pulse wave',dc:'DC level',noise:'White noise',custom:'Custom waveform'};
const $ = id => document.getElementById(id);
$('amplitudeUnitBtn').textContent=DEFAULT_VALUES.amplitudeUnit;$('frequencyUnitBtn').textContent=DEFAULT_VALUES.frequencyUnit;$('periodUnitBtn').textContent=DEFAULT_VALUES.periodUnit;document.querySelector('.voltage-unit-button[data-input="highInput"]').textContent=DEFAULT_VALUES.highLevelUnit;document.querySelector('.voltage-unit-button[data-input="lowInput"]').textContent=DEFAULT_VALUES.lowLevelUnit;document.querySelector('.voltage-unit-button[data-input="offsetInput"]').textContent=DEFAULT_VALUES.offsetUnit;

function setTheme(theme) {
  document.documentElement.dataset.theme=theme;
  localStorage.setItem('arbdraw-theme',theme);
  document.querySelectorAll('.theme-option').forEach(button=>button.classList.toggle('active',button.dataset.theme===theme));
}
setTheme(localStorage.getItem('arbdraw-theme')||'dark');
document.querySelectorAll('.theme-option').forEach(button=>button.addEventListener('click',()=>setTheme(button.dataset.theme)));
function showToast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function renderDocument(){
  document.querySelector('.document-name').value=projectDocument.name;document.querySelector('.document-name').readOnly=true;document.querySelector('.document-name').classList.remove('editing');
  $('highInput').value=displayVoltage('highInput',state.high);$('lowInput').value=displayVoltage('lowInput',state.low);$('offsetInput').value=displayVoltage('offsetInput',(state.high+state.low)/2);$('amplitudeInput').value=displayAmplitude(state.high-state.low);
  renderFrequency();$('phaseInput').value=state.phase;$('dutyInput').value=state.duty;$('dutyValue').textContent=state.duty+'%';renderTiming();
  document.querySelector('.preset.active')?.classList.remove('active');document.querySelector(`.preset[data-wave="${state.type}"]`)?.classList.add('active');$('propertyTitle').textContent=titles[state.type]||'Custom waveform';updateDutyAvailability(state.type);updateFunctionSelect(state.type);draw();
}
function parseProject(raw){
  if(!raw||raw.schema!=='arbdraw.waveform'||raw.version!==1||!raw.waveform)throw new Error('This is not a supported ArbDraw project.');
  const source=raw.waveform,number=(key,fallback)=>Number.isFinite(Number(source[key]))?Number(source[key]):fallback,defaults=createDefaultDocument().waveform;
  const sampleCount=Math.max(2,Math.round(number('sampleCount',defaults.sampleCount))),sampleRateMSa=Math.max(.000001,number('sampleRateMSa',defaults.sampleRateMSa));
  const values=Array.isArray(source.values)&&source.values.length===sampleCount&&source.values.every(Number.isFinite)?source.values.map(Number):[];
  const importedType=source.type==='free'?'custom':source.type;
  const durationMs=sampleCount/(sampleRateMSa*1000),legacyCycles=Math.max(0,number('cycles',defaults.cycles)),frequencyHz=Math.max(.000001,number('frequencyHz',legacyCycles/(durationMs/1000)));
  return {schema:'arbdraw.waveform',version:1,name:String(raw.name||'Imported waveform').slice(0,120),waveform:{type:titles[importedType]?importedType:'custom',highVoltage:number('highVoltage',defaults.highVoltage),lowVoltage:number('lowVoltage',defaults.lowVoltage),durationMs,sampleRateMSa,frequencyHz,cycles:frequencyHz*durationMs/1000,phaseDegrees:number('phaseDegrees',defaults.phaseDegrees),dutyCyclePercent:Math.min(95,Math.max(5,number('dutyCyclePercent',defaults.dutyCyclePercent))),sampleCount,values}};
}
function loadProject(raw){projectDocument=parseProject(raw);state.history=[];state.redo=[];renderDocument();if(!state.data.length)generate();else pushHistory();showToast('Project opened')}

const projectNameInput=document.querySelector('.document-name');
let projectNameBeforeEdit=projectDocument.name;
function beginProjectNameEdit(){if(!projectNameInput.readOnly)return;projectNameBeforeEdit=projectDocument.name;projectNameInput.readOnly=false;projectNameInput.classList.add('editing');projectNameInput.focus();projectNameInput.select()}
function commitProjectNameEdit(cancel=false){if(projectNameInput.readOnly)return;const nextName=cancel?projectNameBeforeEdit:projectNameInput.value.trim();projectDocument.name=nextName||'Untitled project';projectNameInput.value=projectDocument.name;projectNameInput.readOnly=true;projectNameInput.classList.remove('editing')}
projectNameInput.addEventListener('click',beginProjectNameEdit);
projectNameInput.addEventListener('blur',()=>commitProjectNameEdit());
projectNameInput.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();projectNameInput.blur()}if(event.key==='Escape'){event.preventDefault();commitProjectNameEdit(true);projectNameInput.blur()}});
$('newBtn').onclick=()=>{projectDocument=createDefaultDocument();state.history=[];state.redo=[];renderDocument();generate();showToast('New project created')};
$('saveBtn').onclick=()=>{projectDocument.name=document.querySelector('.document-name').value.trim()||'Untitled waveform';const json=JSON.stringify(projectDocument,null,2),blob=new Blob([json],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=projectDocument.name.replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()+'.arbdraw.json';a.click();URL.revokeObjectURL(a.href);showToast('Project JSON downloaded')};
$('openBtn').onclick=()=>{$('projectJsonInput').value='';$('openError').textContent='';$('projectFileInput').value='';$('openDialog').showModal()};
$('chooseProjectBtn').onclick=()=>$('projectFileInput').click();
$('projectFileInput').onchange=async event=>{const file=event.target.files[0];if(file){$('projectJsonInput').value=await file.text();$('openError').textContent=''}};
$('importProjectBtn').onclick=()=>{try{loadProject(JSON.parse($('projectJsonInput').value));$('openDialog').close()}catch(error){$('openError').textContent=error instanceof SyntaxError?'The pasted text is not valid JSON.':error.message}};

function generate(type=state.type,recordHistory=true) {
  state.type=type; const n=state.samples, mid=(state.high+state.low)/2, amp=(state.high-state.low)/2, phase=state.phase*Math.PI/180;
  state.data=Array.from({length:n},(_,i)=>{ const t=i/(n-1), p=(t*state.cycles+state.phase/360)%1; switch(type){
    case 'sine': return mid+amp*Math.sin(2*Math.PI*state.cycles*t+phase);
    case 'square': return p<state.duty/100?state.high:state.low;
    case 'triangle': return mid+amp*(1-4*Math.abs(p-.5));
    case 'ramp': return state.low+(state.high-state.low)*p;
    case 'pulse': return p<state.duty/100?state.high:state.low;
    case 'dc': return mid;
    case 'noise': return mid+(Math.random()*2-1)*amp;
    default: return mid;
  }});if(recordHistory)pushHistory();draw();if(!$('samplesView').classList.contains('hidden'))renderSamples();
}
function cloneWaveform(source=projectDocument.waveform){return {...source,values:[...source.values]}}
function restoreWaveform(snapshot){projectDocument.waveform=cloneWaveform(snapshot);renderDocument()}
function pushHistory(){state.history.push(cloneWaveform());if(state.history.length>30)state.history.shift();state.redo=[]}
function resizeCanvas(target,render){const r=target.getBoundingClientRect(),d=devicePixelRatio||1;if(target.width!==Math.round(r.width*d)||target.height!==Math.round(r.height*d)){target.width=Math.round(r.width*d);target.height=Math.round(r.height*d)}render()}
function resize(){resizeCanvas(canvas,draw);if(!$('waveformView').classList.contains('hidden'))resizeCanvas(scopeCanvas,drawScope)}
function voltageBounds(){if(state.high!==state.low)return {high:state.high,low:state.low};const span=Math.max(5,Math.abs(state.high));return {high:state.high+span,low:state.low-span}}
function draw(){ const w=canvas.width,h=canvas.height,d=devicePixelRatio||1; if(!w||!h)return; ctx.clearRect(0,0,w,h); ctx.fillStyle='#090d0f';ctx.fillRect(0,0,w,h); const pad={l:58*d,r:18*d,t:20*d,b:39*d},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b,bounds=voltageBounds();
  ctx.font=`${10*d}px ui-monospace`;ctx.lineWidth=1*d;ctx.textAlign='right';ctx.textBaseline='middle';
  for(let y=0;y<=8;y++){const py=pad.t+ph*y/8, val=bounds.high-(bounds.high-bounds.low)*y/8;ctx.strokeStyle=y===4?'#49605f':'#223033';ctx.beginPath();ctx.moveTo(pad.l,py);ctx.lineTo(w-pad.r,py);ctx.stroke();ctx.fillStyle='#718083';ctx.fillText(val.toFixed(1),pad.l-9*d,py)}
  ctx.textAlign='center';ctx.textBaseline='top';for(let x=0;x<=10;x++){const px=pad.l+pw*x/10;ctx.strokeStyle=x===0?'#405053':'#1e2c2f';ctx.beginPath();ctx.moveTo(px,pad.t);ctx.lineTo(px,h-pad.b);ctx.stroke();ctx.fillStyle='#718083';ctx.fillText((state.duration*x/10).toFixed(2),px,h-pad.b+10*d)}
  if(!state.data.length)return;ctx.save();ctx.beginPath();ctx.rect(pad.l,pad.t,pw,ph);ctx.clip();ctx.strokeStyle=DEFAULT_VALUES.editorColor;ctx.shadowColor=DEFAULT_VALUES.editorColor;ctx.shadowBlur=5*d;ctx.lineWidth=1.5*d;ctx.beginPath();state.data.forEach((v,i)=>{const x=pad.l+pw*i/(state.data.length-1),y=pad.t+(bounds.high-v)/(bounds.high-bounds.low)*ph;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.restore();drawCustomPreview();if(!$('waveformView').classList.contains('hidden'))drawScope(); }
function nextUpper125(value){if(!Number.isFinite(value)||value<=0)return 1;const exponent=Math.floor(Math.log10(value)),power=10**exponent,normalized=value/power;for(const step of [1,2,5])if(step>=normalized-1e-12)return step*power;return 10*power}
function fittedVerticalScale(){return nextUpper125(Math.max(.000001,Math.abs(state.high-scopeState.verticalPosition),Math.abs(state.low-scopeState.verticalPosition))/4)}
function refreshScopeVertical(){scopeState.voltsPerDiv=fittedVerticalScale();scopeState.fitted=true;$('scopeVoltsDiv').value=Number((scopeState.voltsPerDiv/scopeVoltageUnitScale).toPrecision(8));drawScope()}
function scopeTimeUnitFor(milliseconds){if(milliseconds>=1000)return {scale:1000,label:'s/div'};if(milliseconds>=1)return {scale:1,label:'ms/div'};if(milliseconds>=.001)return {scale:.001,label:'µs/div'};if(milliseconds>=.000001)return {scale:.000001,label:'ns/div'};return {scale:1e-9,label:'ps/div'}}
function renderScopeTime(){const unit=scopeTimeUnitFor(scopeState.timePerDivMs);scopeTimeUnitScaleMs=unit.scale;$('scopeTimeUnitBtn').textContent=unit.label;$('scopeTimeDiv').value=Number((scopeState.timePerDivMs/unit.scale).toPrecision(8))}
function fittedScopeTime(){return Math.min(1000,Math.max(1e-9,nextUpper125(state.duration*scopeState.cycles/10)))}
function refreshScopeTime(){scopeState.timePerDivMs=fittedScopeTime();scopeState.fitted=true;renderScopeTime();drawScope()}
function refreshScope(){scopeState.voltsPerDiv=fittedVerticalScale();scopeState.timePerDivMs=fittedScopeTime();scopeState.fitted=true;$('scopeVoltsDiv').value=Number((scopeState.voltsPerDiv/scopeVoltageUnitScale).toPrecision(8));renderScopeTime();drawScope()}
function drawScope(){const w=scopeCanvas.width,h=scopeCanvas.height,d=devicePixelRatio||1;if(!w||!h)return;if(!scopeState.fitted)refreshScope();const voltsPerDiv=Math.max(1e-12,scopeState.voltsPerDiv),timePerDiv=Math.max(1e-12,scopeState.timePerDivMs),mid=scopeState.verticalPosition,pad={l:62*d,r:18*d,t:20*d,b:39*d},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b,timeSpan=timePerDiv*10,voltageSpan=voltsPerDiv*8;scopeCtx.clearRect(0,0,w,h);scopeCtx.fillStyle='#090d0f';scopeCtx.fillRect(0,0,w,h);scopeCtx.font=`${10*d}px ui-monospace`;scopeCtx.lineWidth=d;scopeCtx.textBaseline='middle';scopeCtx.textAlign='right';for(let y=0;y<=8;y++){const py=pad.t+ph*y/8,value=mid+voltageSpan/2-y*voltsPerDiv;scopeCtx.strokeStyle=y===4?'#49605f':'#223033';scopeCtx.beginPath();scopeCtx.moveTo(pad.l,py);scopeCtx.lineTo(w-pad.r,py);scopeCtx.stroke();scopeCtx.fillStyle='#718083';scopeCtx.fillText(Number(value.toPrecision(4)),pad.l-9*d,py)}scopeCtx.textAlign='center';scopeCtx.textBaseline='top';for(let x=0;x<=10;x++){const px=pad.l+pw*x/10,time=x*timePerDiv;scopeCtx.strokeStyle=x===0?'#405053':'#1e2c2f';scopeCtx.beginPath();scopeCtx.moveTo(px,pad.t);scopeCtx.lineTo(px,h-pad.b);scopeCtx.stroke();scopeCtx.fillStyle='#718083';scopeCtx.fillText(Number(time.toPrecision(4)),px,h-pad.b+10*d)}if(!state.data.length)return;scopeCtx.save();scopeCtx.beginPath();scopeCtx.rect(pad.l,pad.t,pw,ph);scopeCtx.clip();scopeCtx.strokeStyle=DEFAULT_VALUES.waveformColor;scopeCtx.shadowColor=DEFAULT_VALUES.waveformColor;scopeCtx.shadowBlur=5*d;scopeCtx.lineWidth=1.5*d;scopeCtx.beginPath();for(let cycle=0;cycle<scopeState.cycles;cycle++)state.data.forEach((value,index)=>{const time=cycle*state.duration+index/(state.data.length-1)*state.duration,x=pad.l+time/timeSpan*pw,y=pad.t+(mid+voltageSpan/2-value)/voltageSpan*ph;index||cycle?scopeCtx.lineTo(x,y):scopeCtx.moveTo(x,y)});scopeCtx.stroke();scopeCtx.restore()}
function canvasPoint(e){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1,p={l:58*d,r:18*d,t:20*d,b:39*d},x=(e.clientX-r.left)*d,y=(e.clientY-r.top)*d,pw=canvas.width-p.l-p.r,ph=canvas.height-p.t-p.b,bounds=voltageBounds();return {i:Math.max(0,Math.min(state.samples-1,Math.round((x-p.l)/pw*(state.samples-1)))),v:Math.max(bounds.low,Math.min(bounds.high,bounds.high-(y-p.t)/ph*(bounds.high-bounds.low)))};}
function editAt(pt,last){if(state.tool==='pan')return;if(state.tool==='erase')pt.v=(state.high+state.low)/2;if(state.tool==='line'&&state.lineStart){const a=state.lineStart,b=pt,lo=Math.min(a.i,b.i),hi=Math.max(a.i,b.i);for(let i=lo;i<=hi;i++)state.data[i]=a.v+(b.v-a.v)*(i-a.i)/(b.i-a.i||1)}else if(last){const lo=Math.min(last.i,pt.i),hi=Math.max(last.i,pt.i);for(let i=lo;i<=hi;i++)state.data[i]=last.v+(pt.v-last.v)*(i-last.i)/(pt.i-last.i||1)}else state.data[pt.i]=pt.v;draw();}
const dutyDisabledTypes=new Set(['custom','sine','triangle','ramp','dc','noise']);
function updateDutyAvailability(type){const disabled=dutyDisabledTypes.has(type);$('dutyInput').disabled=disabled;$('dutyInput').closest('.range-label').classList.toggle('disabled',disabled)}
function selectPreset(type){document.querySelector('.preset.active')?.classList.remove('active');document.querySelector(`.preset[data-wave="${type}"]`)?.classList.add('active');$('propertyTitle').textContent=titles[type];updateDutyAvailability(type);updateFunctionSelect(type)}
function markCustom(){if(state.type!=='custom'){state.type='custom';selectPreset('custom')}}
canvas.addEventListener('pointerdown',e=>{markCustom();state.drawing=true;canvas.setPointerCapture(e.pointerId);const p=canvasPoint(e);if(state.high===state.low&&state.tool!=='pan'){state.high=Math.max(state.high,p.v);state.low=Math.min(state.low,p.v);$('highInput').value=displayVoltage('highInput',state.high);$('lowInput').value=displayVoltage('lowInput',state.low);$('amplitudeInput').value=displayAmplitude(state.high-state.low);$('offsetInput').value=displayVoltage('offsetInput',(state.high+state.low)/2)}state.lineStart=state.tool==='line'?p:null;state.lastPoint=p;editAt(p)});
canvas.addEventListener('pointermove',e=>{const p=canvasPoint(e);$('cursorReadout').style.display='block';$('cursorReadout').innerHTML=`${(p.i/(state.samples-1)*state.duration).toFixed(3)} ms &nbsp; ${p.v.toFixed(3)} V`;if(state.drawing){editAt(p,state.tool==='pencil'||state.tool==='erase'?state.lastPoint:null);state.lastPoint=p}});
canvas.addEventListener('pointerup',e=>{if(state.drawing&&state.tool==='line')editAt(canvasPoint(e));if(state.drawing)pushHistory();state.drawing=false;state.lineStart=null});canvas.addEventListener('pointerleave',()=>{$('cursorReadout').style.display='none'});

function drawMini(c,type){const x=c.getContext('2d'),w=c.width=110,h=c.height=42;x.strokeStyle='#ff6b2c';x.lineWidth=2;x.beginPath();for(let i=0;i<w;i++){let t=i/(w-1),p=(t*2)%1,y=.5;if(type==='sine')y=.5-.34*Math.sin(t*Math.PI*4);if(type==='square'||type==='pulse')y=p<.5?.2:.8;if(type==='triangle')y=.2+.6*Math.abs(2*p-1);if(type==='ramp')y=.8-.6*p;if(type==='dc')y=.5;if(type==='noise')y=.2+Math.random()*.6;if(type==='custom')y=.5;i?x.lineTo(i,y*h):x.moveTo(i,y*h)}x.stroke()}
function updateFunctionSelect(type){const label=type.charAt(0).toUpperCase()+type.slice(1),button=$('functionSelectBtn');button.querySelector('span').textContent=label;drawMini(button.querySelector('canvas'),type);$('functionSelectMenu').querySelectorAll('[data-wave]').forEach(option=>option.setAttribute('aria-checked',String(option.dataset.wave===type)))}
function closeFunctionSelectMenu(){$('functionSelectMenu').classList.remove('open');$('functionSelectBtn').setAttribute('aria-expanded','false')}
$('functionSelectBtn').onclick=event=>{event.stopPropagation();const button=$('functionSelectBtn'),menu=$('functionSelectMenu'),rect=button.getBoundingClientRect();menu.style.left=Math.min(rect.left,innerWidth-180)+'px';menu.classList.add('open');menu.style.top=Math.min(rect.bottom+4,innerHeight-menu.offsetHeight-8)+'px';button.setAttribute('aria-expanded','true')};
$('functionSelectMenu').querySelectorAll('[data-wave]').forEach(option=>{drawMini(option.querySelector('canvas'),option.dataset.wave);option.onclick=()=>{const type=option.dataset.wave;selectPreset(type);if(type==='custom'){state.type='custom';drawCustomPreview()}else generate(type);refreshScopeTime();closeFunctionSelectMenu()}});
function drawCustomPreview(){if(state.type!=='custom'||!state.data.length)return;const canvases=[$('functionSelectBtn').querySelector('canvas'),$('functionSelectMenu').querySelector('[data-wave="custom"] canvas')],values=state.data;let min=Infinity,max=-Infinity;for(const value of values){if(value<min)min=value;if(value>max)max=value}for(const c of canvases){const x=c.getContext('2d'),w=c.width=110,h=c.height=42,pad=4,span=max-min;x.clearRect(0,0,w,h);x.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--orange').trim()||'#ff6b2c';x.lineWidth=2;x.beginPath();for(let px=0;px<w;px++){const index=Math.round(px/(w-1)*(values.length-1)),y=span?pad+(max-values[index])/span*(h-pad*2):h/2;px?x.lineTo(px,y):x.moveTo(px,y)}x.stroke()}}
document.querySelectorAll('.tool[data-tool]').forEach(b=>b.onclick=()=>{document.querySelector('.tool.active')?.classList.remove('active');b.classList.add('active');state.tool=b.dataset.tool});
function formatSampleTime(index){const seconds=index/(state.samples-1)*state.duration/1000;return seconds===0?'0':seconds.toExponential(9)}
let sampleRenderToken=0;
function renderSamples(){
  const token=++sampleRenderToken,total=state.samples,chunkSize=400,body=$('samplesTableBody'),loading=$('samplesLoading');let index=0;
  $('tableCount').textContent=total.toLocaleString()+' points';body.innerHTML='';loading.classList.remove('done');$('samplesProgress').textContent='0 of '+total.toLocaleString();
  function appendChunk(){if(token!==sampleRenderToken)return;const end=Math.min(index+chunkSize,total),rows=[];for(;index<end;index++)rows.push(`<tr><td>${formatSampleTime(index)}</td><td><input class="sample-voltage" type="number" step="any" data-index="${index}" value="${Number(state.data[index]??0).toPrecision(10)}" aria-label="Voltage at sample ${index+1}"></td></tr>`);body.insertAdjacentHTML('beforeend',rows.join(''));$('samplesProgress').textContent=index.toLocaleString()+' of '+total.toLocaleString();if(index<total)requestAnimationFrame(appendChunk);else loading.classList.add('done')}
  requestAnimationFrame(appendChunk);
}
function renderJson(){const text=JSON.stringify(projectDocument,null,2),lines=text.split('\n').length,bytes=new TextEncoder().encode(text).byteLength;$('jsonOutput').textContent=text;$('jsonStats').textContent=`${lines.toLocaleString()} lines · ${bytes.toLocaleString()} bytes`}
function setEditorTab(tab){for(const name of ['editor','waveform','samples','json']){const active=name===tab;$(name+'Tab').classList.toggle('active',active);$(name+'Tab').setAttribute('aria-selected',String(active));$(name+'View').classList.toggle('hidden',!active)}if(tab==='samples')requestAnimationFrame(renderSamples);else sampleRenderToken++;if(tab==='editor')resize();if(tab==='waveform')requestAnimationFrame(()=>{resizeCanvas(scopeCanvas,drawScope);refreshScope()});if(tab==='json')renderJson()}
$('editorTab').onclick=()=>setEditorTab('editor');$('waveformTab').onclick=()=>setEditorTab('waveform');$('samplesTab').onclick=()=>setEditorTab('samples');$('jsonTab').onclick=()=>setEditorTab('json');
$('scopeRefreshBtn').onclick=refreshScopeTime;
$('scopeVerticalRefreshBtn').onclick=refreshScopeVertical;
for(const [id,key] of [['scopeVoltsDiv','voltsPerDiv'],['scopeTimeDiv','timePerDivMs']]){$(id).addEventListener('change',()=>{const value=Number($(id).value),scale=id==='scopeVoltsDiv'?scopeVoltageUnitScale:scopeTimeUnitScaleMs;if(Number.isFinite(value)&&value>0){scopeState[key]=id==='scopeTimeDiv'?Math.min(1000,Math.max(1e-9,nextUpper125(value*scale))):value*scale;scopeState.fitted=true;if(id==='scopeTimeDiv')renderScopeTime();drawScope()}else $(id).value=Number((scopeState[key]/scale).toPrecision(8))});$(id).addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();$(id).blur()}})}
$('scopeVerticalPosition').addEventListener('change',()=>{const value=Number($('scopeVerticalPosition').value);if(Number.isFinite(value)){scopeState.verticalPosition=value*scopePositionUnitScale;drawScope()}else $('scopeVerticalPosition').value=scopeState.verticalPosition/scopePositionUnitScale});$('scopeVerticalPosition').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();$('scopeVerticalPosition').blur()}});
$('scopeVoltageUnitBtn').onclick=event=>{event.stopPropagation();const button=$('scopeVoltageUnitBtn'),menu=$('scopeVoltageUnitMenu'),rect=button.getBoundingClientRect();menu.style.left=Math.min(rect.left,innerWidth-110)+'px';menu.style.top=rect.bottom+4+'px';menu.classList.add('open');button.setAttribute('aria-expanded','true');menu.querySelectorAll('button').forEach(option=>option.setAttribute('aria-checked',String(+option.dataset.scale===scopeVoltageUnitScale)))};
function closeScopeVoltageUnitMenu(){$('scopeVoltageUnitMenu').classList.remove('open');$('scopeVoltageUnitBtn').setAttribute('aria-expanded','false')}
function selectScopeVoltageUnit(scale,label){scopeVoltageUnitScale=scale;$('scopeVoltageUnitBtn').textContent=label;const value=Number($('scopeVoltsDiv').value);if(Number.isFinite(value)&&value>0)scopeState.voltsPerDiv=value*scopeVoltageUnitScale;drawScope();closeScopeVoltageUnitMenu()}
$('scopeVoltageUnitMenu').querySelectorAll('button').forEach(option=>option.onclick=()=>selectScopeVoltageUnit(+option.dataset.scale,option.dataset.label));
const scopeVoltageSuffixes={m:{scale:.001,label:'mV/div'},v:{scale:1,label:'V/div'}};
$('scopeVoltsDiv').addEventListener('keydown',event=>{const unit=scopeVoltageSuffixes[event.key.toLowerCase()];if(!unit||event.ctrlKey||event.metaKey||event.altKey)return;event.preventDefault();selectScopeVoltageUnit(unit.scale,unit.label)});
function closeScopePositionUnitMenu(){$('scopePositionUnitMenu').classList.remove('open');$('scopePositionUnitBtn').setAttribute('aria-expanded','false')}
function selectScopePositionUnit(scale,label){scopePositionUnitScale=scale;$('scopePositionUnitBtn').textContent=label;const value=Number($('scopeVerticalPosition').value);if(Number.isFinite(value))scopeState.verticalPosition=value*scopePositionUnitScale;drawScope();closeScopePositionUnitMenu()}
$('scopePositionUnitBtn').onclick=event=>{event.stopPropagation();const button=$('scopePositionUnitBtn'),menu=$('scopePositionUnitMenu'),rect=button.getBoundingClientRect();menu.style.left=Math.min(rect.left,innerWidth-100)+'px';menu.style.top=rect.bottom+4+'px';menu.classList.add('open');button.setAttribute('aria-expanded','true');menu.querySelectorAll('button').forEach(option=>option.setAttribute('aria-checked',String(+option.dataset.scale===scopePositionUnitScale)))};
$('scopePositionUnitMenu').querySelectorAll('button').forEach(option=>option.onclick=()=>selectScopePositionUnit(+option.dataset.scale,option.dataset.label));
const scopePositionSuffixes={m:{scale:.001,label:'mV'},v:{scale:1,label:'V'}};
$('scopeVerticalPosition').addEventListener('keydown',event=>{const unit=scopePositionSuffixes[event.key.toLowerCase()];if(!unit||event.ctrlKey||event.metaKey||event.altKey)return;event.preventDefault();selectScopePositionUnit(unit.scale,unit.label)});
function closeScopeTimeUnitMenu(){$('scopeTimeUnitMenu').classList.remove('open');$('scopeTimeUnitBtn').setAttribute('aria-expanded','false')}
function selectScopeTimeUnit(scale,label){scopeTimeUnitScaleMs=scale;$('scopeTimeUnitBtn').textContent=label;const value=Number($('scopeTimeDiv').value);if(Number.isFinite(value)&&value>0)scopeState.timePerDivMs=Math.min(1000,value*scopeTimeUnitScaleMs);drawScope();closeScopeTimeUnitMenu()}
$('scopeTimeUnitBtn').onclick=event=>{event.stopPropagation();const button=$('scopeTimeUnitBtn'),menu=$('scopeTimeUnitMenu'),rect=button.getBoundingClientRect();menu.style.left=Math.min(rect.left,innerWidth-110)+'px';menu.style.top=rect.bottom+4+'px';menu.classList.add('open');button.setAttribute('aria-expanded','true');menu.querySelectorAll('button').forEach(option=>option.setAttribute('aria-checked',String(+option.dataset.scale===scopeTimeUnitScaleMs)))};
$('scopeTimeUnitMenu').querySelectorAll('button').forEach(option=>option.onclick=()=>selectScopeTimeUnit(+option.dataset.scale,option.dataset.label));
const scopeTimeSuffixes={p:{scale:1e-9,label:'ps/div'},n:{scale:1e-6,label:'ns/div'},u:{scale:.001,label:'µs/div'},m:{scale:1,label:'ms/div'},s:{scale:1000,label:'s/div'}};
$('scopeTimeDiv').addEventListener('keydown',event=>{const unit=scopeTimeSuffixes[event.key.toLowerCase()];if(!unit||event.ctrlKey||event.metaKey||event.altKey)return;event.preventDefault();selectScopeTimeUnit(unit.scale,unit.label)});
$('scopeCycles').addEventListener('change',()=>{const value=Math.max(1,Math.round(Number($('scopeCycles').value)));if(Number.isFinite(value)){scopeState.cycles=value;$('scopeCycles').value=value;refreshScopeTime()}else $('scopeCycles').value=scopeState.cycles});$('scopeCycles').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();$('scopeCycles').blur()}});
scopeCanvas.addEventListener('pointermove',event=>{const r=scopeCanvas.getBoundingClientRect(),x=Math.max(0,Math.min(1,(event.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(event.clientY-r.top)/r.height)),time=x*scopeState.timePerDivMs*10,voltage=scopeState.verticalPosition+(0.5-y)*scopeState.voltsPerDiv*8;$('scopeCursorReadout').style.display='block';$('scopeCursorReadout').innerHTML=`${time.toPrecision(5)} ms &nbsp; ${voltage.toPrecision(5)} V`});scopeCanvas.addEventListener('pointerleave',()=>{$('scopeCursorReadout').style.display='none'});
$('copyJsonBtn').onclick=async()=>{const text=JSON.stringify(projectDocument,null,2);try{if(navigator.clipboard&&isSecureContext)await navigator.clipboard.writeText(text);else{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove()}showToast('Project JSON copied')}catch{showToast('Could not access the clipboard')}};
function updateSampleVoltage(input,recordHistory=false){const index=+input.dataset.index,value=Number(input.value);if(!Number.isFinite(value))return;state.data[index]=value;state.high=Math.max(state.high,value);state.low=Math.min(state.low,value);$('highInput').value=displayVoltage('highInput',state.high);$('lowInput').value=displayVoltage('lowInput',state.low);$('amplitudeInput').value=displayAmplitude(state.high-state.low);$('offsetInput').value=displayVoltage('offsetInput',(state.high+state.low)/2);markCustom();if(recordHistory)pushHistory();draw()}
$('samplesTableBody').addEventListener('input',event=>{const input=event.target.closest('.sample-voltage');if(input)updateSampleVoltage(input)});
$('samplesTableBody').addEventListener('change',event=>{const input=event.target.closest('.sample-voltage');if(input)updateSampleVoltage(input,true)});
function renderTiming(){state.sampleRate=state.samples/state.duration/1000;$('samplesEdit').value=state.samples;$('rateEdit').value=Number(state.sampleRate.toPrecision(10));const duration=formatDurationParts(state.duration);$('durationEdit').value=duration.value;$('durationUnit').textContent=duration.unit;}
function renderFrequency(){$('frequencyInput').value=displayFrequency(state.frequency);$('periodInput').value=displayPeriod(state.frequency)}
function formatRate(value){return value>=100?value.toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:1}):value>=1?value.toFixed(3):value.toPrecision(4)}
function formatDuration(value){if(value<.001)return (value*1e6).toFixed(2)+' ns';if(value<1)return (value*1000).toFixed(3)+' µs';if(value<1000)return value.toFixed(3)+' ms';return (value/1000).toFixed(3)+' s'}
function formatDurationParts(value){if(value<.001)return {value:(value*1e6).toFixed(2),unit:'ns'};if(value<1)return {value:(value*1000).toFixed(3),unit:'µs'};if(value<1000)return {value:value.toFixed(3),unit:'ms'};return {value:(value/1000).toFixed(3),unit:'s'}}
function syncInputs(){state.high=inputVoltage('highInput');state.low=inputVoltage('lowInput');if(state.high<state.low)[state.high,state.low]=[state.low,state.high];state.frequency=Math.max(.000001,inputFrequency());state.cycles=state.frequency*state.duration/1000;state.phase=+$('phaseInput').value;state.duty=+$('dutyInput').value;$('highInput').value=displayVoltage('highInput',state.high);$('lowInput').value=displayVoltage('lowInput',state.low);$('amplitudeInput').value=displayAmplitude(state.high-state.low);$('offsetInput').value=displayVoltage('offsetInput',(state.high+state.low)/2);$('dutyValue').textContent=state.duty+'%';renderFrequency();renderTiming();}

function commitTimingInput(kind){const input=kind==='rate'?$('rateEdit'):$('samplesEdit'),value=Number(input.value);if(!Number.isFinite(value)||value<=0){renderTiming();return}if(kind==='rate'){if(Math.abs(value-state.sampleRate)<=Math.max(1,state.sampleRate)*1e-10){renderTiming();return}state.sampleRate=Math.max(.000001,value);state.duration=state.samples/(state.sampleRate*1000);state.cycles=state.frequency*state.duration/1000;renderTiming();pushHistory();draw()}else{const samples=Math.max(2,Math.round(value));if(samples===state.samples){renderTiming();return}state.samples=samples;state.duration=state.samples/(state.sampleRate*1000);state.cycles=state.frequency*state.duration/1000;renderTiming();generate()}}
for(const kind of ['rate','samples']){const input=$(kind==='rate'?'rateEdit':'samplesEdit');input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();input.blur()}if(event.key==='Escape'){event.preventDefault();renderTiming();input.blur()}});input.addEventListener('blur',()=>commitTimingInput(kind))}
function nextLower125(value){if(!Number.isFinite(value)||value<=0)return value;const exponent=Math.floor(Math.log10(value)),power=10**exponent,normalized=value/power,epsilon=1e-12;for(const step of [5,2,1])if(step<normalized-epsilon)return step*power;return 5*power/10}
function samplesForOneCycle(rateMSa,frequencyHz){return Math.max(2,Math.ceil(rateMSa*1e6/frequencyHz))}
$('oneCycleBtn').onclick=()=>{let rate=state.sampleRate,samples=samplesForOneCycle(rate,state.frequency),steps=0;while(samples>state.samples&&steps++<100){rate=nextLower125(rate);samples=samplesForOneCycle(rate,state.frequency)}if(!Number.isFinite(rate)||rate<=0||!Number.isFinite(samples)||rate===state.sampleRate&&samples===state.samples)return;state.sampleRate=rate;state.samples=samples;state.duration=state.samples/(state.sampleRate*1000);state.cycles=state.frequency*state.duration/1000;renderTiming();generate();refreshScopeTime()};
function propertiesDiffer(){const values=[inputVoltage('highInput'),inputVoltage('lowInput'),inputFrequency(),+$('phaseInput').value,+$('dutyInput').value],current=[state.high,state.low,state.frequency,state.phase,state.duty];return values.some((value,index)=>!Number.isFinite(value)||Math.abs(value-current[index])>Math.max(1,Math.abs(current[index]))*1e-10)}
function propertiesValid(){return [$('highInput'),$('lowInput'),$('frequencyInput'),$('phaseInput'),$('dutyInput')].every(input=>Number.isFinite(+input.value))&&inputFrequency()>0}
function valueChanged(value,current){return Math.abs(value-current)>Math.max(1,Math.abs(current))*1e-10}
function applyProperties(){
  if(!propertiesValid()||!propertiesDiffer())return;
  const amplitudeChanged=valueChanged(inputVoltage('highInput'),state.high)||valueChanged(inputVoltage('lowInput'),state.low);
  const timingChanged=valueChanged(inputFrequency(),state.frequency)||valueChanged(+$('phaseInput').value,state.phase)||valueChanged(+$('dutyInput').value,state.duty);
  syncInputs();generate();
  if(amplitudeChanged)refreshScopeTime();
  if(timingChanged)refreshScopeVertical();
}
$('dutyInput').oninput=()=>{if($('dutyInput').disabled)return;state.duty=+$('dutyInput').value;$('dutyValue').textContent=state.duty+'%';generate(state.type,false);refreshScopeVertical()};
$('dutyInput').addEventListener('change',()=>pushHistory());
$('frequencyInput').addEventListener('input',()=>{const value=inputFrequency();if(value>0)$('periodInput').value=displayPeriod(value)});
$('periodInput').addEventListener('input',()=>{const value=inputPeriodFrequency();if(value>0)$('frequencyInput').value=displayFrequency(value)});
$('amplitudeInput').oninput=()=>{const mid=(inputVoltage('highInput')+inputVoltage('lowInput'))/2,a=Math.max(0,+$('amplitudeInput').value)*amplitudeUnitScale/2;$('highInput').value=displayVoltage('highInput',mid+a);$('lowInput').value=displayVoltage('lowInput',mid-a)};
$('offsetInput').oninput=()=>{const a=(inputVoltage('highInput')-inputVoltage('lowInput'))/2,m=inputVoltage('offsetInput');$('highInput').value=displayVoltage('highInput',m+a);$('lowInput').value=displayVoltage('lowInput',m-a)};
document.querySelectorAll('.inspector input').forEach(input=>{input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();input.blur()}});input.addEventListener('blur',applyProperties)});
const propertyDefaultMap={highInput:'highLevelV',lowInput:'lowLevelV',offsetInput:'offsetV',amplitudeInput:'amplitudeVpp',frequencyInput:'frequencyHz',periodInput:'frequencyHz',phaseInput:'phaseDegrees',dutyInput:'dutyCyclePercent'};
function setPropertyInputDefault(input){const key=propertyDefaultMap[input.id];if(!key)return;input.value=input.id==='periodInput'?displayPeriod(DEFAULT_VALUES.frequencyHz):input.id==='frequencyInput'?displayFrequency(DEFAULT_VALUES.frequencyHz):input.id==='amplitudeInput'?displayAmplitude(DEFAULT_VALUES.amplitudeVpp):voltageUnitScales[input.id]?displayVoltage(input.id,DEFAULT_VALUES[key]):DEFAULT_VALUES[key];input.dispatchEvent(new Event('input',{bubbles:true}));applyProperties()}
$('defaultAllBtn').onclick=()=>{$('highInput').value=displayVoltage('highInput',DEFAULT_VALUES.highLevelV);$('lowInput').value=displayVoltage('lowInput',DEFAULT_VALUES.lowLevelV);$('offsetInput').value=displayVoltage('offsetInput',DEFAULT_VALUES.offsetV);$('amplitudeInput').value=displayAmplitude(DEFAULT_VALUES.amplitudeVpp);$('frequencyInput').value=displayFrequency(DEFAULT_VALUES.frequencyHz);$('periodInput').value=displayPeriod(DEFAULT_VALUES.frequencyHz);$('phaseInput').value=DEFAULT_VALUES.phaseDegrees;$('dutyInput').value=DEFAULT_VALUES.dutyCyclePercent;$('dutyValue').textContent=DEFAULT_VALUES.dutyCyclePercent+'%';applyProperties()};
let contextPropertyInput=null;
document.querySelectorAll('.inspector input').forEach(input=>input.addEventListener('contextmenu',event=>{event.preventDefault();contextPropertyInput=input;const menu=$('propertyContextMenu'),width=150,height=42;menu.style.left=Math.min(event.clientX,innerWidth-width-8)+'px';menu.style.top=Math.min(event.clientY,innerHeight-height-8)+'px';menu.classList.add('open');$('setFieldDefaultBtn').focus()}));
function closePropertyContextMenu(){$('propertyContextMenu').classList.remove('open')}
$('setFieldDefaultBtn').onclick=()=>{if(contextPropertyInput)setPropertyInputDefault(contextPropertyInput);closePropertyContextMenu()};
function closeAmplitudeUnitMenu(){$('amplitudeUnitMenu').classList.remove('open');$('amplitudeUnitBtn').setAttribute('aria-expanded','false')}
$('amplitudeUnitBtn').onclick=event=>{event.stopPropagation();const button=$('amplitudeUnitBtn'),menu=$('amplitudeUnitMenu'),rect=button.getBoundingClientRect();menu.style.left=Math.min(rect.left,innerWidth-100)+'px';menu.style.top=rect.bottom+4+'px';menu.classList.add('open');button.setAttribute('aria-expanded','true');menu.querySelectorAll('button').forEach(option=>option.setAttribute('aria-checked',String(+option.dataset.scale===amplitudeUnitScale)))};
function selectAmplitudeUnit(scale,label){amplitudeUnitScale=scale;$('amplitudeUnitBtn').textContent=label;$('amplitudeInput').dispatchEvent(new Event('input',{bubbles:true}));applyProperties();closeAmplitudeUnitMenu()}
$('amplitudeUnitMenu').querySelectorAll('button').forEach(option=>option.onclick=()=>selectAmplitudeUnit(+option.dataset.scale,option.dataset.label));
const amplitudeSuffixes={u:{scale:.000001,label:'µVpp'},m:{scale:.001,label:'mVpp'},v:{scale:1,label:'Vpp'}};
$('amplitudeInput').addEventListener('keydown',event=>{const unit=amplitudeSuffixes[event.key.toLowerCase()];if(!unit||event.ctrlKey||event.metaKey||event.altKey)return;event.preventDefault();selectAmplitudeUnit(unit.scale,unit.label)});
let activeVoltageUnitInput=null;
function closeVoltageUnitMenu(){$('voltageUnitMenu').classList.remove('open');document.querySelectorAll('.voltage-unit-button').forEach(button=>button.setAttribute('aria-expanded','false'))}
document.querySelectorAll('.voltage-unit-button').forEach(button=>button.onclick=event=>{event.stopPropagation();activeVoltageUnitInput=button.dataset.input;const menu=$('voltageUnitMenu'),rect=button.getBoundingClientRect();menu.style.left=Math.min(rect.left,innerWidth-100)+'px';menu.style.top=rect.bottom+4+'px';menu.classList.add('open');button.setAttribute('aria-expanded','true');menu.querySelectorAll('button').forEach(option=>option.setAttribute('aria-checked',String(+option.dataset.scale===voltageUnitScales[activeVoltageUnitInput])))});
function selectVoltageUnit(inputId,scale,label){voltageUnitScales[inputId]=scale;document.querySelector(`.voltage-unit-button[data-input="${inputId}"]`).textContent=label;$(inputId).dispatchEvent(new Event('input',{bubbles:true}));applyProperties();closeVoltageUnitMenu()}
$('voltageUnitMenu').querySelectorAll('button').forEach(option=>option.onclick=()=>{if(activeVoltageUnitInput)selectVoltageUnit(activeVoltageUnitInput,+option.dataset.scale,option.dataset.label)});
const voltageSuffixes={u:{scale:.000001,label:'µV'},m:{scale:.001,label:'mV'},v:{scale:1,label:'V'}};
for(const inputId of Object.keys(voltageUnitScales))$(inputId).addEventListener('keydown',event=>{const unit=voltageSuffixes[event.key.toLowerCase()];if(!unit||event.ctrlKey||event.metaKey||event.altKey)return;event.preventDefault();selectVoltageUnit(inputId,unit.scale,unit.label)});
function closeTimingUnitMenus(){for(const id of ['frequency','period']){$(id+'UnitMenu').classList.remove('open');$(id+'UnitBtn').setAttribute('aria-expanded','false')}}
function openTimingUnitMenu(kind){const button=$(kind+'UnitBtn'),menu=$(kind+'UnitMenu'),rect=button.getBoundingClientRect(),scale=kind==='frequency'?frequencyUnitScale:periodUnitScale;menu.style.left=Math.min(rect.left,innerWidth-100)+'px';menu.style.top=rect.bottom+4+'px';menu.classList.add('open');button.setAttribute('aria-expanded','true');menu.querySelectorAll('button').forEach(option=>option.setAttribute('aria-checked',String(+option.dataset.scale===scale)))}
function selectTimingUnit(kind,scale,label){if(kind==='frequency')frequencyUnitScale=scale;else periodUnitScale=scale;$(kind+'UnitBtn').textContent=label;$(kind+'Input').dispatchEvent(new Event('input',{bubbles:true}));applyProperties();closeTimingUnitMenus()}
for(const kind of ['frequency','period']){$(kind+'UnitBtn').onclick=event=>{event.stopPropagation();openTimingUnitMenu(kind)};$(kind+'UnitMenu').querySelectorAll('button').forEach(option=>option.onclick=()=>selectTimingUnit(kind,+option.dataset.scale,option.dataset.label))}
const frequencySuffixes={h:{scale:1,label:'Hz'},H:{scale:1,label:'Hz'},k:{scale:1000,label:'kHz'},K:{scale:1000,label:'kHz'},m:{scale:.001,label:'mHz'},M:{scale:1000000,label:'MHz'},g:{scale:1000000000,label:'GHz'},G:{scale:1000000000,label:'GHz'}},periodSuffixes={s:{scale:1,label:'s'},m:{scale:.001,label:'ms'},M:{scale:1000000,label:'Ms'},u:{scale:.000001,label:'µs'},U:{scale:.000001,label:'µs'},n:{scale:.000000001,label:'ns'},N:{scale:.000000001,label:'ns'}};
$('frequencyInput').addEventListener('keydown',event=>{const unit=frequencySuffixes[event.key];if(!unit||event.ctrlKey||event.metaKey||event.altKey)return;event.preventDefault();selectTimingUnit('frequency',unit.scale,unit.label)});
$('periodInput').addEventListener('keydown',event=>{const unit=periodSuffixes[event.key];if(!unit||event.ctrlKey||event.metaKey||event.altKey)return;event.preventDefault();selectTimingUnit('period',unit.scale,unit.label)});
document.addEventListener('pointerdown',event=>{if(!$('propertyContextMenu').contains(event.target))closePropertyContextMenu();if(!$('amplitudeUnitMenu').contains(event.target)&&event.target!==$('amplitudeUnitBtn'))closeAmplitudeUnitMenu();if(!$('voltageUnitMenu').contains(event.target)&&!event.target.closest?.('.voltage-unit-button'))closeVoltageUnitMenu();if(!event.target.closest?.('#frequencyUnitMenu,#periodUnitMenu,#frequencyUnitBtn,#periodUnitBtn'))closeTimingUnitMenus();if(!event.target.closest?.('#scopeVoltageUnitMenu,#scopeVoltageUnitBtn'))closeScopeVoltageUnitMenu();if(!event.target.closest?.('#scopePositionUnitMenu,#scopePositionUnitBtn'))closeScopePositionUnitMenu();if(!event.target.closest?.('#scopeTimeUnitMenu,#scopeTimeUnitBtn'))closeScopeTimeUnitMenu();if(!event.target.closest?.('#functionSelectMenu,#functionSelectBtn'))closeFunctionSelectMenu()});document.addEventListener('keydown',event=>{if(event.key==='Escape'){closePropertyContextMenu();closeAmplitudeUnitMenu();closeVoltageUnitMenu();closeTimingUnitMenus();closeScopeVoltageUnitMenu();closeScopePositionUnitMenu();closeScopeTimeUnitMenu();closeFunctionSelectMenu()}});window.addEventListener('blur',()=>{closePropertyContextMenu();closeAmplitudeUnitMenu();closeVoltageUnitMenu();closeTimingUnitMenus();closeScopeVoltageUnitMenu();closeScopePositionUnitMenu();closeScopeTimeUnitMenu();closeFunctionSelectMenu()});
function undoWaveform(){if(state.history.length>1){state.redo.push(state.history.pop());restoreWaveform(state.history.at(-1))}}
function redoWaveform(){if(state.redo.length){const snapshot=state.redo.pop();state.history.push(cloneWaveform(snapshot));restoreWaveform(snapshot)}}
$('undoBtn').onclick=undoWaveform;$('redoBtn').onclick=redoWaveform;
document.addEventListener('keydown',event=>{const editing=event.target.matches?.('input, textarea, select, [contenteditable="true"]');if(editing)return;const modifier=event.ctrlKey||event.metaKey;if(!modifier)return;const key=event.key.toLowerCase();if(key==='z'&&!event.shiftKey){event.preventDefault();undoWaveform()}else if((key==='z'&&event.shiftKey)||(key==='y'&&event.ctrlKey)){event.preventDefault();redoWaveform()}});
$('zoomIn').onclick=()=>{state.high*=.8;state.low*=.8;draw()};$('zoomOut').onclick=()=>{state.high*=1.25;state.low*=1.25;draw()};$('fitView').onclick=()=>{syncInputs();draw()};
$('exportBtn').onclick=()=>{const csv='time_s,voltage_v\n'+state.data.map((v,i)=>`${i/(state.samples-1)*state.duration/1000},${v}`).join('\n'),blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='arbdraw-waveform.csv';a.click();URL.revokeObjectURL(a.href);showToast('Waveform exported as CSV')};
new ResizeObserver(resize).observe(canvas);new ResizeObserver(()=>{if(!$('waveformView').classList.contains('hidden'))resizeCanvas(scopeCanvas,drawScope)}).observe(scopeCanvas);renderDocument();generate();
